### PR TITLE
Add Scale Parameter to FFMPEG

### PR DESCRIPTION
**Pull request by jesi-rgb**
# What?
This PR simply adds a scale argument to the `FFMPEGExport` class, like this:

```python
FFMPEGExport(animation, passes, scale=1.3).prores().write()
```

This allows the user to work on a sketch at their default size, but then be able to output a higher quality video if needed. 

# Why?
I found this useful when working on a 1080x1080 (default) sized scene and then wanting to output, say, 2000x2000 for maximum juice. 

Changing the size would mess up the whole scene since the glyphs would stay the same size, but the viewport grew larger. I wanted the behaviour of the argument "-ps 1.5" but on export.

# How?

This PR only adds the string `scale=iw*{self.scale}:ih*{self.scale}` to the filter_complex with the corresponding boilerplate needed for it. Pretty handy and almost for free!

### CODE REVIEW

**Comment by jesi-rgb** [comment]
Upon reviewing my commit, it seems as though my editor has formatted the whole file using [Black](https://black.readthedocs.io/en/stable/), causing a much bigger diff than the actual, tiny change I made.

@stenson please let me know if I should commit a change without formatting. I believe that a formatter is quite useful for open source, but I want to be respectful of your project's rules!

**Comment by stenson** [comment]
Thanks for the PR! I'm not quite sure I understand the use-case, though — you want to export a video file that's a larger resolution than the rendered frames?

As for the formatter, agreed that there should be something standard for Coldtype, unfortunately it makes a lot of crazy formatting choices (as an idiomatic choice for creative-coding), so I'd have to configure a formatter to capture all of that. Probably worth doing but not a priority to me.

**Comment by jesi-rgb** [comment]
Yup, I didn't give it much thought. It technically worked for me but it's not the behavior I expected.

What I actually want is a way of being able to output higher resolution video, regardless of the declared video size by the user.

Again, my main problem is if I declare a different size in the @animation decorator, the window grows larger but my elements do not. How could we achieve such thing? Any ideas?

And regarding the formatter: I completely understand. I'll do my best to follow your rules next time. For now, we can close this and maybe discuss in an issue!

Thanks so much, Rob!

**Comment by stenson** [comment]
mm, got it — yeah that's an interesting issue. I'm not sure the situation you're describing is solvable directly (or at least I can't think of how to do it yet), but there are shortcuts to scale/zoom the preview window, by hitting +/- (well, I guess = and - technically, since they don't require shift) — does that help with your use-case at all?

**Pull request closed without merging**
